### ISSUE TITLE
Text not centered within Border when using Padding and Flex

### ISSUE THREAD

**Issue by afandria** [flutter/engine#1294] opened 2015-09-22 23:09 UTC
Possibly related text-align issues: #1257 #1260

I tested with the following:
```
import 'package:sky/rendering.dart';
import 'package:sky/widgets.dart';

class ProblematicApp extends App {

  Widget build() {
    return new Container(
      decoration: new BoxDecoration(backgroundColor: new Color(0xFF666666)),
      child: new Flex([new FlatButton(
        child: new Container(
          decoration: new BoxDecoration(
            border: new Border.all(
              width: 3.0,
              color: new Color(0xFF0000FF)
            )
          ),
          padding: new EdgeDims.all(10.0), // If padding is removed, the text's border is fine even in a Flex.
          child: new Text("Pass") // If Text is replaced with an image, the image's border is fine even with Padding + Flex.
        )
      )]) // If the Flex is removed, the text's border looks fine even with padding.
    );
  }
}

void main() {
  runApp(new ProblematicApp());
}
```

I got this bad image, where the border is the text is down-shifted compared to the border.
![screenshot_2015-09-22-15-57-46](https://cloud.githubusercontent.com/assets/2432033/10034257/12efc07e-6144-11e5-8df6-bf0cb7c570a3.png)

I did 3 alternative experiments, all of which look like they have the proper alignment.
* Remove the Padding
![screenshot_2015-09-22-15-59-13](https://cloud.githubusercontent.com/assets/2432033/10034261/19d27fb2-6144-11e5-8a22-d585f885a9b5.png)

* Remove the Flex
![screenshot_2015-09-22-15-58-23](https://cloud.githubusercontent.com/assets/2432033/10034269/269f17d2-6144-11e5-8861-9a93047ed019.png)

* Replace Text with Image `new NetworkImage(src: "images/default/classic/up/s1.png")`
![screenshot_2015-09-22-16-03-16](https://cloud.githubusercontent.com/assets/2432033/10034270/2a25d080-6144-11e5-8fdd-25173e6d2679.png)

**Comment by jason-simmons** [comment] 2015-09-29 23:46
I took a look at this and compared the Flex to the version without the Flex

In the Flex case:
  * the RenderFlex is laid out with a BoxConstraints specifying (592.0<=h<592.0)
    * but RenderFlex.performLayout is calling child.layout() passing a BoxConstraints with (0.0<=h<592.0)
  * the FlatButton builds a Container with a hardcoded height of 36
    * this shows up in the render tree as a RenderConstrainedBox whose additionalConstraints is BoxConstraints(36.0<=h<36.0)
  * RenderConstrainedBox.performLayout calls BoxConstraints.enforce to merge the (0.0<=h<592.0) with (36.0<=h<36.0)
    * the result is (36.0<=h<36.0)
    * this is passed down to the descendants, eventually reaching the RenderPadding
    * RenderPadding subtracts 13 pixels (10 for the padding, 3 for the border) and passes (0.0<=h<10.0) to the RenderParagraph
    * RenderParagraph has a height of 10 pixels and is centered vertically, but it doesn't clip the text that it paints.  So you see the misaligned text outside its bounds.

In the case without Flex:
  * the ancestors of the FlatButton's rendering objects specify a BoxConstraints with (576.0<=h<576.0)
  * the FlatButton's RenderConstrainedBox calls BoxConstraints(36.0<=h<36.0).enforce(BoxConstraints(576.0<=h<576.0))
    * it's unclear what should happen here given that these two constraints are incompatible
    * but due to a quirk of the BoxConstraints.enforce implementation, the result is (576.0<=h<576.0)
  * RenderParagraph eventually gets a BoxConstraints with (0.0<=h<550.0), and it can give itself enough height to fully render the text

**Comment by Hixie** [comment] 2015-09-30 17:40
The only thing I'm surprised by here is that the constraint passed from Flex to the child is 0.0<=h<592.0. I'd have thought it would be 0.0<=h<double.INFINITY.

I hadn't realised there was a FlatButton in the original test. The FlatButton is the cause of the overflow. FlatButtons are defined by material design specs to be 36 pixels high. If the text style is too big to fit in that, then it's gonna overflow.

The real bug here I guess is that MaterialButton doesn't provide a default text style for its buttons (I have a patch in progress to fix that).

**Comment by jason-simmons** [comment] 2015-09-30 18:05
The (0.0<=h<592.0) constraint is coming from the code in RenderFlex.performLayout that sets the innerConstraints in the cross direction

          switch (_direction) {
            case FlexDirection.horizontal:
              innerConstraints = new BoxConstraints(maxHeight: constraints.maxHeight);
              break;

Looks like this is working as intended.  Closing.

**Closed by jason-simmons** 2015-09-30 18:05 UTC

**Comment by afandria** [comment] 2015-09-30 18:30
The constraint code may be working as intended, but as-is, the rendering is still not correct.

What do I need to do to get the Text to be properly aligned? Should I stop using FlatButtons? Wait until buttons get a default Text style?

**Comment by Hixie** [comment] 2015-09-30 20:07
Just don't put padding in the button. There's also the issue with the wrong font being chosen, I'm tracking that down separately.
