### ISSUE TITLE
Long urls should be broken up in a rational way

### ISSUE THREAD

**Issue by turu** [flutter/engine#1155] opened 2015-09-14 16:08 UTC
**Steps to reproduce:**
**1.** Create a ```Text``` with a string long enough so that it has to be wrapped. Let this string contain no white spaces.

**Expected result:**
**1.** The ```Text``` should be nicely broken up into two or more lines.

**Actual result:**
**1.** The ```Text``` looks weird, broken up into many lines.

**Example:**
```Dart
class UrlDisplayerApp extends App {
  @override
  Widget build() {
    return new Container(
        decoration: new BoxDecoration(backgroundColor: RedAccent[700]),
        child: new Container(
            child: new Text(
                "https://a.very.long.url.should.be.broken.up.in.a.rational.way",
                style: typo.white.body2),
            padding: const EdgeDims.all(50.0)));
  }
}
```

The above will result in:
![screenshot_2015-09-14-11-50-49](https://cloud.githubusercontent.com/assets/3460101/9854784/dde61b9c-5b0a-11e5-9f41-151faa5c9faf.png)

If this turns out to be not really a bug, but rather lack of feature, perhaps we can think if it makes sense to treat characters like ```.:/``` as proper line break candidates (in the absence of whitespaces).

**Comment by abarth** [comment] 2015-10-04 23:26
Closing as duplicate of #1190

**Closed by abarth** 2015-10-04 23:26 UTC
Labels: bug, sky engine api
