### ISSUE TITLE
Handle Android URL intents

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1459] opened 2015-10-02 18:27 UTC
We should be able to follow a link to a specific stock in the stocks app, going to the '/stock/ABC' route for instance.

Launching the app from the home screen icon should go to the '/' route, not reopen whatever the most recently opened route was. (Test: go to a stock from another app, like a browser, then hit home, then hit stocks, then hit back - you shouldn't end up at the browser.)

**Comment by abarth** [comment] 2015-10-04 23:29
Closing as duplicate of #776

**Closed** 2015-10-14 22:14 UTC
Labels: affects high-profile demos, enhancement, framework, services
